project_id: '494961'
commit_message: 'chore(i18n-crowdin): new translations for %original_file_name% (%language%)'
append_commit_message: false

files:
  - source: locales/en-US/**/*.json
    translation: locales/%locale%/**/%original_file_name%
