version: '2.4'

services:
  # yarn build && yarn start
  # bot:
  #   env_file: "./.env.local"
  #   ports: 
  #     - "2292"

  exportapi:
    image: ghcr.io/fyko/export-api:latest
    ports:
      - "2324:80"
    expose:
      - "2324"

  postgres:
    restart: unless-stopped
    build:
      context: docker/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: doctordoctor
      POSTGRES_DB: archive_utility
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
