name: "Setup Volta"
description: "Setup Volta"
runs:
  using: "composite"
  steps:
    - uses: volta-cli/action@v3
      with:
        node-version: 18.x

    - name: Cache Volta
      uses: actions/cache@v2
      with:
        path: ~/.volta
        key: volta-${{ runner.os }}-${{ hashFiles('yarn.lock', 'Cargo.lock') }}
        restore-keys: |
          volta-${{ runner.os }}-
