name: "Setup Rust"
description: "Setup Rust (cargo) with cache enabled"
runs:
  using: "composite"
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: stable
        override: true

    - name: Load Cargo Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
