name: Testing (archive-utility)

on:
  push:
    paths-ignore:
      - 'display/**'
  pull_request:
    paths-ignore:
      - 'display/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Run ESlint and TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3

      - name: Install dependencies
        uses: ./.github/actions/yarn

      - name: Run ESLint
        run: yarn lint

      - name: Register Problem Matcher
        run: echo "##[add-matcher].github/tsc.json"

      - name: Run TypeScript compiler
        run: yarn build

      
