name: Deploy to Cloudflare Workers

on:
  
  push:
    branches:
      - main
    paths:
      - 'display/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/rust

      - name: Publish to Production
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.WORKERS_API_TOKEN }}
          environment: production
          workingDirectory: ./display
