name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'display/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Volta
        uses: ./.github/actions/volta

      - name: Setup Rust
        uses: ./.github/actions/rust

      - name: Install wrangler
        run: volta install wrangler

      - name: Publish to Production
        env: 
          CLOUDFLARE_API_TOKEN: ${{ secrets.WORKERS_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        working-directory: ./display
        run: wrangler deploy --env production
