name: Testing (display)

on:
  push:
    paths:
      - 'display/**'
  pull_request:
    paths:
      - 'display/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    name: Lint, Format, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/rust

      - uses: actions-rs/cargo@v1
        name: Run Formatter
        with:
          command: fmt
          args: --check

      - uses: actions-rs/cargo@v1
        name: Run Clippy
        with:
          command: clippy

      - uses: actions-rs/cargo@v1
        name: Run Tests
        with:
          command: test
          args: --all --all-features

      - uses: actions-rs/cargo@v1
        name: Run Build
        with:
          command: build
          args: --all --all-features
